name: Patch build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install python3-numpy
        
      - name: Build patch archive
        run: bash build.sh
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
         files: patch.zip
         tag_name: v${{ github.run_number }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
